# Generated by Django 2.2.7 on 2019-11-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191106_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='news.tag', verbose_name='分类'),
        ),
    ]
