# Generated by Django 2.2.7 on 2019-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191111_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='发表日期'),
        ),
    ]
