# Generated by Django 2.2.7 on 2020-03-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200305_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='news_cover', verbose_name='封面'),
        ),
    ]
