# Generated by Django 2.2.7 on 2020-07-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200305_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
    ]
