# Generated by Django 2.2.7 on 2019-11-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('outline', models.CharField(max_length=200, verbose_name='概述')),
                ('date', models.DateField(verbose_name='获奖日期')),
                ('members', models.CharField(max_length=100, verbose_name='参加成员')),
                ('counselor', models.CharField(max_length=100, verbose_name='指导老师')),
                ('news_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.news')),
            ],
        ),
    ]
