# Generated by Django 2.2.7 on 2019-11-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propaganda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='news_id',
            new_name='news',
        ),
    ]
