# Generated by Django 2.2.7 on 2019-11-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propaganda', '0002_auto_20191106_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='level',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
