# Generated by Django 2.2.7 on 2019-11-11 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propaganda', '0003_achievement_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.news', verbose_name='关联新闻'),
        ),
    ]
