# Generated by Django 2.2.7 on 2019-11-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propaganda', '0006_auto_20191111_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': '成就', 'verbose_name_plural': '成就'},
        ),
    ]
