# Generated by Django 2.2.7 on 2019-11-06 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='电子邮箱')),
                ('identity', models.IntegerField(verbose_name='身份')),
                ('student_id', models.CharField(max_length=11, unique=True, verbose_name='学号')),
                ('user_class', models.CharField(max_length=20, verbose_name='专业班级')),
                ('telephone', models.IntegerField(unique=True, verbose_name='电话')),
                ('duty', models.CharField(max_length=30, verbose_name='职务')),
                ('introduction', models.TextField(verbose_name='个人介绍')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='编辑日期')),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='提交时间')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
