# Generated by Django 2.2.7 on 2019-11-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191106_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_shown',
            field=models.BooleanField(default=False, verbose_name='在成员列表中展示'),
        ),
    ]
