# Generated by Django 2.2.7 on 2019-11-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_is_shown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='duty',
            field=models.IntegerField(choices=[(1, '总负责人'), (2, '负责人'), (3, '指导老师'), (4, '管理人员'), (5, '队长'), (6, '团支部书记'), (7, '宣传部长'), (8, '技术培训部长'), (9, '组织部长'), (10, '超算基地正式成员'), (11, '超算预备队员'), (12, '超算爱好者')], max_length=30, verbose_name='职务'),
        ),
    ]
