# Generated by Django 2.2.7 on 2019-11-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191107_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(1, '通过'), (2, '审核中'), (3, '未通过')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='identity',
            field=models.IntegerField(choices=[(0, '教师'), (1, '学生')], verbose_name='身份'),
        ),
    ]
