# Generated by Django 2.2.7 on 2019-11-13 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191108_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='个人介绍'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联账户'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='专业班级'),
        ),
    ]
