# Generated by Django 2.2.7 on 2019-11-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191114_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='头像'),
        ),
    ]
