# Generated by Django 2.2.7 on 2020-03-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191118_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='电子邮箱'),
        ),
        migrations.AddField(
            model_name='application',
            name='major',
            field=models.IntegerField(choices=[(1, '统招'), (2, '宣传')], default=None, verbose_name='方向'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default=None, max_length=5, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='student_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='application',
            name='user_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='专业班级'),
        ),
    ]
