# Generated by Django 2.2.7 on 2019-11-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(max_length=20, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='source',
            field=models.CharField(max_length=20, verbose_name='来源'),
        ),
    ]
