# Generated by Django 2.2.7 on 2019-11-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20191114_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
