# Generated by Django 2.2.7 on 2020-03-05 06:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20191116_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
