# Generated by Django 2.2.7 on 2019-11-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img_filename', models.CharField(max_length=255, verbose_name='图片文件名')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
                ('link', models.CharField(max_length=50, verbose_name='链接到的页面')),
            ],
        ),
    ]
