# Generated by Django 2.2.7 on 2020-03-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20191114_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carousel',
        ),
    ]
