# Generated by Django 2.2.7 on 2020-07-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0003_delete_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img_filename', models.CharField(max_length=255, verbose_name='图片文件名')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
                ('link', models.CharField(max_length=50, verbose_name='链接到的页面')),
                ('content_class', models.IntegerField(choices=[(1, '基地介绍'), (2, '新闻'), (3, '指导老师'), (4, '成员'), (5, '公告'), (6, '文章'), (7, '关于我们'), (8, '保留'), (9, '保留')], verbose_name='内容类别')),
                ('place', models.IntegerField(choices=[(1, '顶端'), (2, '中部')], verbose_name='安放位置')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
