# Generated by Django 2.2.7 on 2020-07-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img_filename',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='link',
            field=models.CharField(max_length=50, verbose_name='文本编号'),
        ),
    ]
